const listAlamat = [
    {
        id_alamat: 1,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Babarsari No. 1",
        status_default: true,
        id_pembeli: 1,
    },
    {
        id_alamat: 2,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Kaliurang Km. 5",
        status_default: false,
        id_pembeli: 2,
    },
    {
        id_alamat: 3,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Gejayan No. 21",
        status_default: false,
        id_pembeli: 1,
    },
    {
        id_alamat: 4,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Solo No. 10",
        status_default: true,
        id_pembeli: 3,
    },
    {
        id_alamat: 5,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Wonosari Km. 8",
        status_default: false,
        id_pembeli: 2,
    },
    {
        id_alamat: 6,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Affandi No. 5",
        status_default: false,
        id_pembeli: 3,
    },
    {
        id_alamat: 7,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Palagan Tentara Pelajar",
        status_default: true,
        id_pembeli: 4,
    },
    {
        id_alamat: 8,
        nama_alamat: "Rumah",
        detail_alamat: "Perumahan Griya Citra Asri Blok B2",
        status_default: true,
        id_pembeli: 5,
    },
    {
        id_alamat: 9,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Monjali No. 17",
        status_default: true,
        id_pembeli: 6,
    },
    {
        id_alamat: 10,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Ringroad Utara No. 3",
        status_default: true,
        id_pembeli: 7,
    },
    {
        id_alamat: 11,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Godean Km. 4",
        status_default: false,
        id_pembeli: 4,
    },
    {
        id_alamat: 12,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Imogiri Timur No. 2",
        status_default: false,
        id_pembeli: 5,
    },
    {
        id_alamat: 13,
        nama_alamat: "Rumah",
        detail_alamat: "Komplek Puri Indah No. 12",
        status_default: true,
        id_pembeli: 8,
    },
    {
        id_alamat: 14,
        nama_alamat: "Rumah",
        detail_alamat: "Perumahan Citra Garden Blok A1",
        status_default: false,
        id_pembeli: 6,
    },
    {
        id_alamat: 15,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Magelang Km. 6",
        status_default: false,
        id_pembeli: 7,
    },
    {
        id_alamat: 16,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Kapten Piere Tendean",
        status_default: true,
        id_pembeli: 9,
    },
    {
        id_alamat: 17,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Rajawali No. 8",
        status_default: false,
        id_pembeli: 8,
    },
    {
        id_alamat: 18,
        nama_alamat: "Kantor",
        detail_alamat: "Jl. Sudirman No. 15",
        status_default: true,
        id_pembeli: 10,
    },
    {
        id_alamat: 19,
        nama_alamat: "Kantor",
        detail_alamat: "Jl. Malioboro No. 1",
        status_default: false,
        id_pembeli: 9,
    },
    {
        id_alamat: 20,
        nama_alamat: "Kantor",
        detail_alamat: "Jl. Adisutjipto Km. 3",
        status_default: false,
        id_pembeli: 10,
    },
    {
        id_alamat: 21,
        nama_alamat: "Kantor",
        detail_alamat: "Jl. Seturan No. 11",
        status_default: false,
        id_pembeli: 1,
    },
    {
        id_alamat: 22,
        nama_alamat: "Kantor",
        detail_alamat: "Jl. Laksda Adisucipto No. 20",
        status_default: true,
        id_pembeli: 2,
    },
    {
        id_alamat: 23,
        nama_alamat: "Kantor",
        detail_alamat: "Ruko Mataram Square Blok C",
        status_default: false,
        id_pembeli: 3,
    },
    {
        id_alamat: 24,
        nama_alamat: "Kantor",
        detail_alamat: "Jl. Solo Baru No. 9",
        status_default: false,
        id_pembeli: 4,
    },
    {
        id_alamat: 25,
        nama_alamat: "Kantor",
        detail_alamat: "Jl. Dr. Sutomo No. 5",
        status_default: false,
        id_pembeli: 5,
    },
    {
        id_alamat: 26,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Kaliurang Km 12",
        status_default: true,
        id_pembeli: 11,
    },
    {
        id_alamat: 27,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Magelang Km 9",
        status_default: true,
        id_pembeli: 12,
    },
    {
        id_alamat: 28,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Solo Km 14",
        status_default: true,
        id_pembeli: 13,
    },
    {
        id_alamat: 29,
        nama_alamat: "Kantor",
        detail_alamat: "Jl. Gejayan No. 35",
        status_default: false,
        id_pembeli: 11,
    },
    {
        id_alamat: 30,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Seturan No. 45",
        status_default: true,
        id_pembeli: 14,
    },
    {
        id_alamat: 31,
        nama_alamat: "Kantor",
        detail_alamat: "Jl. Monjali No. 25",
        status_default: false,
        id_pembeli: 12,
    },
    {
        id_alamat: 32,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Affandi No. 15",
        status_default: false,
        id_pembeli: 13,
    },
    {
        id_alamat: 33,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Ringroad Selatan No. 10",
        status_default: true,
        id_pembeli: 15,
    },
    {
        id_alamat: 34,
        nama_alamat: "Kantor",
        detail_alamat: "Jl. Sudirman No. 20",
        status_default: false,
        id_pembeli: 14,
    },
    {
        id_alamat: 35,
        nama_alamat: "Rumah",
        detail_alamat: "Jl. Godean Km 5",
        status_default: false,
        id_pembeli: 15,
    },
];

export async function alamatSeeding(prismaClient) {
    await prismaClient.alamat.createMany({
        data: listAlamat,
    });
}
