const listBarang = [
  {
    prefix: "B",
    id_barang: 1,
    nama_barang: "Blender Philips HR2056",
    deskripsi:
      "Blender multifungsi dengan pisau stainless steel, cocok untuk jus dan bumbu",
    harga: 450000,
    status: "TERSEDIA",
    garansi: new Date("2024-12-15"),
    berat: 2.5,
    id_kategori: 1,
  },
  {
    prefix: "K",
    id_barang: 2,
    nama_barang: "Kaos Polos Cotton Combed",
    deskripsi:
      "Kaos polos warna hitam, bahan lembut, nyaman dipakai sehari-hari",
    harga: 75000,
    status: "TERSEDIA",
    garansi: null,
    berat: 0.2,
    id_kategori: 2,
  },
  {
    prefix: "M",
    id_barang: 3,
    nama_barang: "Meja Lipat Kayu",
    deskripsi:
      "Meja lipat minimalis, cocok untuk belajar atau bekerja dari rumah",
    harga: 250000,
    status: "TERSEDIA",
    garansi: null,
    berat: 5.0,
    id_kategori: 3,
  },
  {
    prefix: "B",
    id_barang: 4,
    nama_barang: "Buku Novel Laskar Pelangi",
    deskripsi:
      "Novel best-seller karya Andrea Hirata, kondisi belum dibuka plastiknya",
    harga: 95000,
    status: "TERJUAL",
    garansi: null,
    berat: 0.4,
    id_kategori: 4,
  },
  {
    prefix: "A",
    id_barang: 5,
    nama_barang: "Action Figure Iron Man",
    deskripsi:
      "Action figure original Marvel, detail tinggi, cocok untuk koleksi",
    harga: 350000,
    status: "TERJUAL",
    garansi: new Date("2024-11-01"),
    berat: 0.5,
    id_kategori: 5,
  },
  {
    prefix: "S",
    id_barang: 6,
    nama_barang: "Stroller Bayi Pliko",
    deskripsi: "Stroller ringan dengan desain modern, mudah dilipat dan dibawa",
    harga: 1200000,
    status: "TERSEDIA",
    garansi: new Date("2025-12-25"),
    berat: 7.0,
    id_kategori: 6,
  },
  {
    prefix: "V",
    id_barang: 7,
    nama_barang: "Velg Mobil Ring 15 Bekas",
    deskripsi:
      "Velg mobil bekas kondisi mulus, cocok untuk modifikasi mobil sedan",
    harga: 1800000,
    status: "TERSEDIA",
    garansi: new Date("2024-06-05"),
    berat: 8.0,
    id_kategori: 7,
  },
  {
    prefix: "P",
    id_barang: 8,
    nama_barang: "Pot Tanaman Keramik",
    deskripsi:
      "Pot tanaman aesthetic berdiameter 20 cm, cocok untuk dekorasi taman",
    harga: 65000,
    status: "TERJUAL",
    garansi: new Date("2025-07-15"),
    berat: 1.2,
    id_kategori: 8,
  },
  {
    prefix: "P",
    id_barang: 9,
    nama_barang: "Printer Canon Pixma G3010",
    deskripsi: "Printer multifungsi untuk cetak, scan, dan copy, hemat tinta",
    harga: 2300000,
    status: "TERSEDIA",
    garansi: new Date("2024-03-10"),
    berat: 6.0,
    id_kategori: 9,
  },
  {
    prefix: "H",
    id_barang: 10,
    nama_barang: "Hair Dryer Panasonic EH-ND11",
    deskripsi:
      "Hair dryer bekas kondisi baik, daya 400W, cocok untuk penggunaan harian",
    harga: 120000,
    status: "TERSEDIA",
    garansi: null,
    berat: 0.6,
    id_kategori: 10,
  },
  {
    prefix: "B",
    id_barang: 11,
    nama_barang: "Buku Tulis Sinar Dunia 58 Lembar",
    deskripsi:
      "Buku tulis bekas tapi bersih, hanya beberapa lembar terpakai, cocok untuk anak sekolah",
    harga: 3000,
    status: "TERSEDIA",
    garansi: null,
    berat: 0.2,
    id_kategori: 4,
  },
  {
    prefix: "K",
    id_barang: 12,
    nama_barang: "Kursi Lipat Plastik Napolly",
    deskripsi: "Kursi lipat bekas, kokoh dan ringan, cocok untuk acara outdoor",
    harga: 45000,
    status: "TERSEDIA",
    garansi: new Date("2025-05-20"),
    berat: 2.5,
    id_kategori: 3,
  },
  {
    prefix: "S",
    id_barang: 13,
    nama_barang: "Sepatu Sneakers Adidas Neo",
    deskripsi:
      "Sepatu bekas ukuran 42, kondisi masih layak pakai, nyaman dan ringan",
    harga: 175000,
    status: "TERSEDIA",
    garansi: new Date("2026-03-20"),
    berat: 1.2,
    id_kategori: 2,
  },
  {
    prefix: "T",
    id_barang: 14,
    nama_barang: "Tas Ransel Eiger 25L",
    deskripsi: "Tas bekas kondisi bagus, cocok untuk kuliah atau traveling",
    harga: 120000,
    status: "TERSEDIA",
    garansi: null,
    berat: 0.8,
    id_kategori: 2,
  },
  {
    prefix: "P",
    id_barang: 15,
    nama_barang: "Panci Stainless Steel 24cm",
    deskripsi:
      "Panci bekas, mulus tanpa goresan, cocok untuk masak sup atau mie",
    harga: 50000,
    status: "TERSEDIA",
    garansi: null,
    berat: 1.3,
    id_kategori: 3,
  },
  {
    prefix: "M",
    id_barang: 16,
    nama_barang: "Meja Belajar Lipat Kayu",
    deskripsi: "Meja belajar bekas, bahan kayu ringan, cocok untuk anak-anak",
    harga: 85000,
    status: "TERSEDIA",
    garansi: null,
    berat: 3.5,
    id_kategori: 3,
  },
  {
    prefix: "G",
    id_barang: 17,
    nama_barang: "Gitar Akustik Yamaha F310",
    deskripsi: "Gitar bekas, suara masih jernih, cocok untuk pemula",
    harga: 450000,
    status: "TERSEDIA",
    garansi: new Date("2025-11-20"),
    berat: 2.2,
    id_kategori: 5,
  },
  {
    prefix: "J",
    id_barang: 18,
    nama_barang: "Jaket Parka Uniqlo Pria",
    deskripsi: "Jaket bekas, bahan waterproof, cocok untuk musim hujan",
    harga: 140000,
    status: "TERSEDIA",
    garansi: null,
    berat: 1.1,
    id_kategori: 2,
  },
  {
    prefix: "O",
    id_barang: 19,
    nama_barang: "One Piece Volume 1 - Komik",
    deskripsi: "Komik bekas, halaman lengkap, cover masih bagus",
    harga: 10000,
    status: "TERSEDIA",
    garansi: null,
    berat: 0.3,
    id_kategori: 5,
  },
  {
    prefix: "L",
    id_barang: 20,
    nama_barang: "Lampu Tidur Karakter Hello Kitty",
    deskripsi: "Lampu tidur bekas lucu, cocok untuk kamar anak, nyala normal",
    harga: 25000,
    status: "TERSEDIA",
    garansi: null,
    berat: 0.5,
    id_kategori: 3,
  },
  {
    prefix: "L",
    id_barang: 21,
    nama_barang: "Laptop Lenovo ThinkPad E470",
    deskripsi:
      "Laptop bekas performa bagus, cocok untuk pelatihan komputer remaja",
    harga: 2700000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 1.8,
    id_kategori: 3,
  },
  {
    prefix: "P",
    id_barang: 22,
    nama_barang: "Printer & Scanner Canon MG2570S",
    deskripsi:
      "Printer dan scanner bekas, cocok untuk administrasi kantor atau sekolah",
    harga: 650000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 4.2,
    id_kategori: 9,
  },
  {
    prefix: "K",
    id_barang: 23,
    nama_barang: "Kasur Lipat",
    deskripsi: "Kasur lipat bekas dan selimut bersih",
    harga: 300000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 5.5,
    id_kategori: 6,
  },
  {
    prefix: "D",
    id_barang: 24,
    nama_barang: "Dumbell bekas",
    deskripsi:
      "Dumbell bekas 5kg - 20kg, cocok untuk aktivitas komunitas pemuda",
    harga: 200000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 3.0,
    id_kategori: 7,
  },
  {
    prefix: "R",
    id_barang: 25,
    nama_barang: "Rak Buku dan Lemari",
    deskripsi: "Rak buku dan lemari untuk perpustakaan mini",
    harga: 120000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 10,
    id_kategori: 4,
  },
  {
    prefix: "S",
    id_barang: 26,
    nama_barang: "Sepeda Anak",
    deskripsi: "Sepeda bekas untuk anak-anak",
    harga: 300000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 7,
    id_kategori: 6,
  },
  {
    prefix: "P",
    id_barang: 27,
    nama_barang: "Alat Pertukangan",
    deskripsi: "Peralatan pertukangan lengkap dengan palu dan gergaji",
    harga: 18000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 8,
    id_kategori: 5,
  },
  {
    prefix: "S",
    id_barang: 28,
    nama_barang: "Sound System",
    deskripsi: "Speaker, Mic, Amplifier",
    harga: 2500000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 5,
    id_kategori: 3,
  },
  {
    prefix: "W",
    id_barang: 29,
    nama_barang: "Whiteboard",
    deskripsi: "Whiteboard dan spidol untuk kelas belajar",
    harga: 100000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 3,
    id_kategori: 1,
  },
  {
    prefix: "P",
    id_barang: 30,
    nama_barang: "Proyektor Mini",
    deskripsi: "Proyektor mini dengan 4000 lumen",
    harga: 2000000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 1,
    id_kategori: 1,
  },
  {
    prefix: "M",
    id_barang: 31,
    nama_barang: "Mesin Laminating A4",
    deskripsi:
      "Mesin laminating untuk dokumen ukuran A4, cocok untuk kantor dan sekolah",
    harga: 350000,
    status: "KEMBALI",
    garansi: null,
    berat: 2.5,
    id_kategori: 9,
  },
  {
    prefix: "T",
    id_barang: 32,
    nama_barang: "Tripod Kamera Aluminium",
    deskripsi: "Tripod kamera ringan dan kokoh dengan tinggi maksimal 160cm",
    harga: 175000,
    status: "KEMBALI",
    garansi: new Date("2025-08-05"),
    berat: 1.1,
    id_kategori: 1,
  },
  {
    id_barang: 33,
    nama_barang: "Kamera Canon EOS 600D",
    deskripsi: "Kamera DSLR bekas, kondisi baik, cocok untuk fotografi",
    harga: 3500000,
    status: "TERSEDIA",
    garansi: new Date("2025-10-15 00:00:00.000"),
    berat: 0.6,
    id_kategori: 1,
    prefix: "K",
  },
  {
    id_barang: 34,
    nama_barang: "Jaket Kulit Vintage",
    deskripsi: "Jaket kulit bekas, kondisi mulus, ukuran M",
    harga: 200000,
    status: "TERSEDIA",
    garansi: null,
    berat: 0.8,
    id_kategori: 2,
    prefix: "J",
  },
  {
    id_barang: 35,
    nama_barang: "Rak Sepatu Plastik",
    deskripsi: "Rak sepatu bekas, kapasitas 10 pasang, ringan",
    harga: 50000,
    status: "TERSEDIA",
    garansi: null,
    berat: 1.5,
    id_kategori: 3,
    prefix: "R",
  },
  {
    id_barang: 36,
    nama_barang: "Buku Programming Python",
    deskripsi: "Buku bekas, kondisi baik, cocok untuk belajar coding",
    harga: 80000,
    status: "TERSEDIA",
    garansi: null,
    berat: 0.5,
    id_kategori: 4,
    prefix: "B",
  },
  {
    id_barang: 37,
    nama_barang: "Mainan Lego Star Wars",
    deskripsi: "Mainan bekas, lengkap, cocok untuk koleksi",
    harga: 150000,
    status: "TERJUAL",
    garansi: null,
    berat: 0.4,
    id_kategori: 5,
    prefix: "M",
  },
  {
    id_barang: 38,
    nama_barang: "Kursi Bayi Makan",
    deskripsi: "Kursi makan bayi bekas, kokoh dan bersih",
    harga: 200000,
    status: "TERSEDIA",
    garansi: new Date("2025-12-01 00:00:00.000"),
    berat: 3,
    id_kategori: 6,
    prefix: "K",
  },
  {
    id_barang: 39,
    nama_barang: "Ban Motor Tubeless",
    deskripsi: "Ban motor bekas, ukuran 120/70-17, masih layak",
    harga: 250000,
    status: "TERSEDIA",
    garansi: null,
    berat: 2,
    id_kategori: 7,
    prefix: "B",
  },
  {
    id_barang: 40,
    nama_barang: "Payung Taman Besar",
    deskripsi: "Payung taman bekas, diameter 2m, kondisi baik",
    harga: 300000,
    status: "TERJUAL",
    garansi: new Date("2025-11-20 00:00:00.000"),
    berat: 5,
    id_kategori: 8,
    prefix: "P",
  },
  {
    id_barang: 41,
    nama_barang: "Mesin Fotocopy Mini",
    deskripsi: "Mesin fotocopy bekas, fungsi normal, cocok untuk kantor",
    harga: 1500000,
    status: "TERSEDIA",
    garansi: new Date("2025-09-10 00:00:00.000"),
    berat: 10,
    id_kategori: 9,
    prefix: "M",
  },
  {
    id_barang: 42,
    nama_barang: "Sabun Mandi Cair 1L",
    deskripsi: "Sabun cair bekas isi ulang, aroma lavender",
    harga: 30000,
    status: "TERSEDIA",
    garansi: null,
    berat: 1,
    id_kategori: 10,
    prefix: "S",
  },
  {
    id_barang: 43,
    nama_barang: "Televisi LED 32 Inch",
    deskripsi: "TV LED bekas, layar jernih, untuk donasi komunitas",
    harga: 1200000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 5,
    id_kategori: 1,
    prefix: "T",
  },
  {
    id_barang: 44,
    nama_barang: "Kipas Angin Meja",
    deskripsi: "Kipas angin bekas, fungsi normal, untuk donasi",
    harga: 80000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 1.5,
    id_kategori: 1,
    prefix: "K",
  },
  {
    id_barang: 45,
    nama_barang: "Setrika Uap Philips",
    deskripsi: "Setrika uap bekas, kondisi baik, untuk donasi",
    harga: 150000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 1,
    id_kategori: 1,
    prefix: "S",
  },
  {
    id_barang: 46,
    nama_barang: "Lemari Pakaian Plastik",
    deskripsi: "Lemari plastik bekas, 3 pintu, untuk donasi",
    harga: 250000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 8,
    id_kategori: 3,
    prefix: "L",
  },
  {
    id_barang: 47,
    nama_barang: "Sepatu Olahraga Nike",
    deskripsi: "Sepatu bekas, ukuran 43, kondisi layak, untuk donasi",
    harga: 100000,
    status: "DIDONASIKAN",
    garansi: null,
    berat: 0.7,
    id_kategori: 2,
    prefix: "S",
  },
];

export async function barangSeeding(prismaClient) {
  await prismaClient.barang.createMany({
    data: listBarang,
  });
}
