import bcrypt from "bcrypt";
import { v4 as uuid } from "uuid";

async function generateUserList() {
    const userData = [
        {
            id_user: 1,
            email: "frendy@reusemart.my.id",
            plainPassword: "10101999",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 2,
            email: "alexanderfabian@reusemart.my.id",
            plainPassword: "22082000",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 3,
            email: "stanyslaushary@reusemart.my.id",
            plainPassword: "12072000",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 4,
            email: "sukarjomaja@reusemart.my.id",
            plainPassword: "12082001",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 5,
            email: "enimanari@reusemart.my.id",
            plainPassword: "11092000",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 6,
            email: "putrisakoju@reusemart.my.id",
            plainPassword: "14102002",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 7,
            email: "dewisekira@reusemart.my.id",
            plainPassword: "28022004",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 8,
            email: "ahmadjaya@reusemart.my.id",
            plainPassword: "13112000",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 9,
            email: "fauzaniman@reusemart.my.id",
            plainPassword: "14102001",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 10,
            email: "hugopalimasada@reusemart.my.id",
            plainPassword: "24042004",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 11,
            email: "indahpertiwi@reusemart.my.id",
            plainPassword: "17062004",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 12,
            email: "budisantoso@reusemart.my.id",
            plainPassword: "15052001",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 13,
            email: "rinawulandari@reusemart.my.id",
            plainPassword: "20032002",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 14,
            email: "tinaamelia@reusemart.my.id",
            plainPassword: "25072003",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 15,
            email: "rudihartono@reusemart.my.id",
            plainPassword: "10122002",
            role: "PEGAWAI",
            token: uuid().toString(),
        },
        {
            id_user: 16,
            email: "alyaputri@gmail.com",
            plainPassword: "alyaputri",
            role: "PEMBELI",
            token: uuid().toString(),
        },
        {
            id_user: 17,
            email: "andinugroho@yahoo.com",
            plainPassword: "andinugroho",
            role: "PEMBELI",
            token: uuid().toString(),
        },
        {
            id_user: 18,
            email: "siti@outlook.com",
            plainPassword: "siti",
            role: "PEMBELI",
            token: uuid().toString(),
        },
        {
            id_user: 19,
            email: "budisantoso@hotmail.com",
            plainPassword: "budisantoso",
            role: "PEMBELI",
            token: uuid().toString(),
        },
        {
            id_user: 20,
            email: "dinaauliarahma@gmail.com",
            plainPassword: "dinaauliarahma",
            role: "PEMBELI",
            token: uuid().toString(),
        },
        {
            id_user: 21,
            email: "rudi@gmail.com",
            plainPassword: "rudi",
            role: "PEMBELI",
            token: uuid().toString(),
        },
        {
            id_user: 22,
            email: "liakartika@yahoo.com",
            plainPassword: "liakartika",
            role: "PEMBELI",
            token: uuid().toString(),
        },
        {
            id_user: 23,
            email: "ahmadzaki@outlook.com",
            plainPassword: "ahmadzaki",
            role: "PEMBELI",
            token: uuid().toString(),
        },
        {
            id_user: 24,
            email: "melatinurhasanah@gmail.com",
            plainPassword: "melatinurhasanah",
            role: "PEMBELI",
            token: uuid().toString(),
        },
        {
            id_user: 25,
            email: "joko@hotmail.com",
            plainPassword: "joko",
            role: "PEMBELI",
            token: uuid().toString(),
        },
        {
            id_user: 26,
            email: "jokosantoso@gmail.com",
            plainPassword: "jokosantoso",
            role: "PENITIP",
            token: uuid().toString(),
        },
        {
            id_user: 27,
            email: "sitiaminah@yahoo.com",
            plainPassword: "sitiaminah",
            role: "PENITIP",
            token: uuid().toString(),
        },
        {
            id_user: 28,
            email: "budihartono@outlook.com",
            plainPassword: "budihartono",
            role: "PENITIP",
            token: uuid().toString(),
        },
        {
            id_user: 29,
            email: "rinawulandari@gmail.com",
            plainPassword: "rinawulandari",
            role: "PENITIP",
            token: uuid().toString(),
        },
        {
            id_user: 30,
            email: "ahmadyani@hotmail.com",
            plainPassword: "ahmadyani",
            role: "PENITIP",
            token: uuid().toString(),
        },
        {
            id_user: 31,
            email: "dewilestari@yahoo.com",
            plainPassword: "dewilestari",
            role: "PENITIP",
            token: uuid().toString(),
        },
        {
            id_user: 32,
            email: "ekoprasetyo@gmail.com",
            plainPassword: "ekoprasetyo",
            role: "PENITIP",
            token: uuid().toString(),
        },
        {
            id_user: 33,
            email: "linamarlina@outlook.com",
            plainPassword: "linamarlina",
            role: "PENITIP",
            token: uuid().toString(),
        },
        {
            id_user: 34,
            email: "fajarnugroho@gmail.com",
            plainPassword: "fajarnugroho",
            role: "PENITIP",
            token: uuid().toString(),
        },
        {
            id_user: 35,
            email: "tinasusanti@gmail.com",
            plainPassword: "tinasusanti",
            role: "PENITIP",
            token: uuid().toString(),
        },
        {
            id_user: 36,
            email: "yayasandharmabakti@gmail.com",
            plainPassword: "yayasandharmabakti",
            role: "ORGANISASI",
            token: uuid().toString(),
        },
        {
            id_user: 37,
            email: "lembagacintakasih@yahoo.com",
            plainPassword: "lembagacintakasih",
            role: "ORGANISASI",
            token: uuid().toString(),
        },
        {
            id_user: 38,
            email: "forumhijauindonesia@outlook.com",
            plainPassword: "forumhijauindonesia",
            role: "ORGANISASI",
            token: uuid().toString(),
        },
        {
            id_user: 39,
            email: "komunitaspedulipendidikan@gmail.com",
            plainPassword: "komunitaspedulipendidikan",
            role: "ORGANISASI",
            token: uuid().toString(),
        },
        {
            id_user: 40,
            email: "baktisosialnusantara@gmail.com",
            plainPassword: "baktisosialnusantara",
            role: "ORGANISASI",
            token: uuid().toString(),
        },
        {
            id_user: 41,
            email: "relawantanggapdarurat@yahoo.com",
            plainPassword: "relawantanggapdarurat",
            role: "ORGANISASI",
            token: uuid().toString(),
        },
        {
            id_user: 42,
            email: "gerakandonordarah@gmail.com",
            plainPassword: "gerakandonordarah",
            role: "ORGANISASI",
            token: uuid().toString(),
        },
        {
            id_user: 43,
            email: "sahabatlansia@outlook.com",
            plainPassword: "sahabatlansia",
            role: "ORGANISASI",
            token: uuid().toString(),
        },
        {
            id_user: 44,
            email: "rumahharapan@gmail.com",
            plainPassword: "rumahharapan",
            role: "ORGANISASI",
            token: uuid().toString(),
        },
        {
            id_user: 45,
            email: "pemudaberkarya@gmail.com",
            plainPassword: "pemudaberkarya",
            role: "ORGANISASI",
            token: uuid().toString(),
        },
    ];

    const listUser = await Promise.all(
        userData.map(async (user) => ({
            id_user: user.id_user,
            email: user.email,
            password: await bcrypt.hash(user.plainPassword, 10),
            role: user.role,
            token: uuid().toString(),
        }))
    );

    return listUser;
}

export async function userSeeding(prismaClient) {
    const users = await generateUserList();
    await prismaClient.user.createMany({
        data: users,
    });
}
